version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./api:/opt/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/opt/app